/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_0af0fbad (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// This file is no longer used - all KV functions are now inline in index.tsx
// Keeping this file for backwards compatibility only

export const set = async (key: string, value: any): Promise<void> => {
  throw new Error("Use inline KV functions in index.tsx");
};

export const get = async (key: string): Promise<any> => {
  throw new Error("Use inline KV functions in index.tsx");
};

export const del = async (key: string): Promise<void> => {
  throw new Error("Use inline KV functions in index.tsx");
};

export const getByPrefix = async (prefix: string): Promise<any[]> => {
  throw new Error("Use inline KV functions in index.tsx");
};
